server:
  port: 8081
  ssl:
    enabled: true
    certificate: "classpath:keys/fullchain1.pem"
    certificate-private-key: "classpath:keys/privkey1.pem"
spring:
  application:
    name: moup-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.1.19:3308/moup
    username: root
    password: root

app:
  admin:
    auth:
      jwt:
        secret: MrLf61DOaUL3rFB7iPaXci33mXd537uCZzHNfJsBE5k=
      login:
        password: Moup123!
  environment:
    production: true
  cors:
    allowed-origins: https://moup.io,https://admin.moup.io:444