spring:
  application:
    name: moup-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/moup
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  web:
    error:
      include-message: always
      include-binding-errors: always