server:
  port: 8080
spring:
  application:
    name: moup-api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/moup
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  web:
    error:
      include-message: always
      include-binding-errors: always

app:
  environment:
    production: false
  http:
    push-host: https://api.moup.io:8081
  cors:
    allowed-origins: http://192.168.1.11:4200

