server:
  port: 8081
  ssl:
    enabled: true
    certificate: "classpath:keys/fullchain1.pem"
    certificate-private-key: "classpath:keys/privkey1.pem"
spring:
  application:
    name: moup-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.17.0.1:3307/moup
    username: root
    password: root

cors:
  allowed-origins: https://moup.io