server:
  port: 8081
spring:
  application:
    name: moup-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.17.0.1:3307/moup
    username: root
    password: root

cors:
  allowed-origins: http://moup.io